version: "3"

networks:
  default:
    external: false

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80"
      - "443:443"
    environment:
      - TZ='Europe/Budapest'
      - WEBPASSWORD=${WEBPASSWORD}
      - DNS1=1.1.1.1
      - DNS2=8.8.8.8
      - API_EXCLUDE_DOMAINS=*.local,*.168.192.in-addr.arpa,*.plex.direct
      - ServerIP=${SERVER_IP}
    extra_hosts:
      - 'plex plex.raspberrypi.local:192.168.19.242'
      - 'torrent torrent.raspberrypi.local:192.168.19.242'
      - 'pihole pihole.raspberrypi.local:192.168.19.242'
      - 'grafana grafana.raspberrypi.local:192.168.19.242'
      - 'homeassistant homeassistant.raspberrypi.local:192.168.19.242'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    networks:
      - default
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: always
    shm_size: 512M
    logging:
      options:
        max-size: '1m'
        max-file: '3'
