version: "3"

services:
  homeassistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homeassistant
    restart: on-failure
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - /dev/bus/usb:/dev/bus/usb
      - /var/run/dbus:/var/run/dbus
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - TZ=Europe/Budapest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 30s
      timeout: 10s
      retries: 6

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    user: "1000:1000"
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/data:/mosquitto/data
    restart: always

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:arm32v6
    container_name: zigbee2mqtt
    restart: always
    network_mode: host
    volumes:
      - ./zigbee2mqtt/data:/app/data
    #devices:
      # CC251
      #- /dev/ttyUSB_cc2531:/dev/ttyACM0
      # CC2530 / GBAN GB2530S
      #- /dev/ttyUSB_cc2530:/dev/ttyACM0
