version: '3'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /home/pi/.docker/config.json:/config.json
    command: --interval 3600 -c
